---
# tasks file for nrser.homebrew-cask
- name: tap caskroom/cask
  homebrew_tap:
    name: caskroom/cask
    state: present
  register: homebrew_cask_tap

- name: update cask via brew update
  command: brew update
  when: homebrew_cask_tap.changed
  